apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: three-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: 543816070942.dkr.ecr.us-east-1.amazonaws.com/product-backend:backend-2f303698c0e157c5f1c5712178f584f810c7a560
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/product
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
