apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 543816070942.dkr.ecr.us-east-1.amazonaws.com/product-frontend:frontend-2f303698c0e157c5f1c5712178f584f810c7a560
          ports:
            - containerPort: 80
